# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pyseatrials',
                'doc_host': 'https://JonnoB.github.io',
                'git_url': 'https://github.com/JonnoB/pyseatrials',
                'lib_path': 'pyseatrials'},
  'syms': {'pyseatrials.core': {'pyseatrials.core.foo': ('core.html#foo', 'pyseatrials/core.py')}}}