# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/98_basic_hydro_functions.ipynb.

# %% auto 0
__all__ = ['dynamic_viscosity', 'kinamatic_visocity_fn', 'reynolds_number_fn', 'froude_number_fn', 'CF_fn',
           'roughness_allowence_fn']

# %% ../nbs/98_basic_hydro_functions.ipynb 3
import numpy as np
import pandas as pd
from fastcore.test import *

# %% ../nbs/98_basic_hydro_functions.ipynb 5
def dynamic_viscosity(salinity:float, #A positive value of the water salinity [g/kg]
                      temperature:float #The temperature in celsius [C]
                     )->float: #returns values in [kg/ms]
    
    "Calculate the dynamic viscosity dependent on temperature and salinity"
    
    mu_w = 4.2844*10**(-5) + 1/(0.157*(temperature + 64.993)**2 - 91.296)
    
    A = 1.541 + 1.998 * temperature * 10**(-2) - 9.52 * temperature**2 * 10 ** (-5)
    B = 7.974 - 7.561 * temperature * 10**(-2) - 7.724 * temperature**2 * 10 ** (-4)
    
    return mu_w * (1 + A*salinity + B*salinity**2)

# %% ../nbs/98_basic_hydro_functions.ipynb 13
def kinamatic_visocity_fn(dynamic_viscosity:float = 1.18e-3, #This value is typically 1.18e-3 [kg/(ms)]
                          water_density:float = 1026 #The density of water under current conditions [kg/m^3]
                         )-> float: #[m^2/s]
    
    "A simple wrapper calculating the ratio of dynamic viscosity and water density"
    
    return dynamic_viscosity/water_density
    

# %% ../nbs/98_basic_hydro_functions.ipynb 20
def reynolds_number_fn(stw:float, #Speed through water [m/s]
                      length:float, #Length of the vessel, $L_{os}$ Length overall submerged is typically used [m]
                      kinamatic_viscosity:float # [m^2/s]
                      )->float: # Reynolds number is dimensionless
    
    "The Reynolds number is a element of fluid dynamics and is often used to predict whether flow is laminar or turbulent"
    
    return stw * length / kinamatic_viscosity
    
    

# %% ../nbs/98_basic_hydro_functions.ipynb 25
def froude_number_fn(stw:float, #speed through water [m/s]
                    length:float,#Length of vessel, typically $L_{wl}$ Length of waterline [m]
                    gravity:float = 9.81 #acceleration due to gravity [m/s^2]
                    )-> float : #The Froude number is a dimensionless value
    
    "The Froude number is useful for calculating the water resistance"
    
    return stw/np.sqrt(gravity * length)

# %% ../nbs/98_basic_hydro_functions.ipynb 30
def CF_fn(reynolds_number:float, #indicating the type of flow of the water
       adjustment_value:float = 0.1194 # An adjustment value applied by testing company. Default if from ITTC 57
      )-> float: #This is a dimensionaless value
    
    "An essential part of calculating the resistance experienced by the ship"
    
    return (1 + adjustment_value) * 0.067 / (np.log10(reynolds_number) -2) ** 2   
    

# %% ../nbs/98_basic_hydro_functions.ipynb 34
def roughness_allowence_fn(
                          length:float, #Length of the vessel at waterline [m]
                          reynolds_number:float, # dimensionless value describing flow properties
                          surface_roughness:float = 150e-6, #The default value is outdated an modern hull covering are likely considerably less rough [m]
                          )-> float: #
    
    ratio_value = surface_roughness / length
    return (11/250)* (ratio_value**(1/3) - 10 * reynolds_number**(-1/3)) + (1/8e3)
    
