# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/98_basic_hydro_functions.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/98_basic_hydro_functions.ipynb 3
import numpy as np
import pandas as pd
from fastcore.test import *
