"""A collection of functions and equations from the main body of ITTC"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_general_functions.ipynb.

# %% auto #0
__all__ = ['knots_to_ms', 'ms_to_knots', 'power_correction', 'shaft_speed_correction', 'wind_resistance',
           'temp_salinity_water_resistance', 'displacement_correction', 'load_datasets']

# %% ../nbs/01_general_functions.ipynb #ce0a62d5-61d4-4d26-9cee-a60af7f0c61e
import numpy as np
import pandas as pd
from fastcore.test import *
import pkgutil
from io import BytesIO

# %% ../nbs/01_general_functions.ipynb #1c9a4345-d033-4f36-a14e-38228502cbd1
def knots_to_ms(knots:float #the speed in knots
               ) -> float: #speed in m/s
    
    "convert knots to m/s"
    
    return knots/1.943844

# %% ../nbs/01_general_functions.ipynb #63d287f1-771a-4dbe-981d-f392b32b859b
def ms_to_knots(ms:float #the speed in m/s
               ) -> float: #speed in knots
    
    "convert knots to m/s"
    
    return ms * 1.943844

# %% ../nbs/01_general_functions.ipynb #3a1536a6
def power_correction(pd_meas:float, #measured shaft power [W]
                     delta_R:float, #increase of resistance due to wind, waves and temperature deviation [N]
                     stw:float, #speed through water [m/s]
                     etaD_id:float, #propulsion efficiency coefficienct in ideal conditions (from model test) [-]
                     shaft_power_overload:float #overload factor from load variation model test [-]
                     ) -> float: #shaft power in ideal conditions [W]
    
    frac = (delta_R * stw) / etaD_id
    shaft_power = 0.5 * (pd_meas - frac + np.sqrt((pd_meas - frac) **2 + 4 * pd_meas * frac * shaft_power_overload))
    
    return shaft_power

# %% ../nbs/01_general_functions.ipynb #3e59bbcb
def shaft_speed_correction(n_ms:float, #measured propeller shaft revolution frequency [1/s]
                           shaft_speed_overload:float, #overload factor derived from load variation model test [-]
                           pd_meas:float, #measured shaft power [W]
                           pd_id:float #shaft power in ideal conditions [W]
                           ) -> float: #propeller shaft revolution frequency in ideal condition [1/s]
    
    frac = (pd_meas - pd_id) / pd_id
    shaft_speed = n_ms / (shaft_speed_overload * frac + 1)
    
    return shaft_speed

# %% ../nbs/01_general_functions.ipynb #b2c4a21f-c717-436c-8428-bf605d4d5e76
def wind_resistance(air_density:float, #Air density [kg/$m^3$]
                   wind_resistance_coef_rel:float, #the coefficient of wind resistance using the relative angle of the wind
                   wind_resistance_coef_zero:float, #the coefficient of wind resistance using angle 0 radians
                   area:float, #The maximum transverse area of the ship exposed to the wind [m^2]
                   relative_wind_speed:float, #Relative wind speed [m/s]
                   sog:float #speed over ground [m/s]
                   
                  )->float: #Air resistance [N]
    "Calculates the air resistance. N.B. SI units must be used. Do not use knots"
    
    wind_resistance_val = 0.5*air_density*area*(wind_resistance_coef_rel*relative_wind_speed**2 - wind_resistance_coef_zero*sog**2)
    
    return wind_resistance_val

# %% ../nbs/01_general_functions.ipynb #3471dc04-b2f8-4d2f-8599-b63d6cb2f89c
def temp_salinity_water_resistance(CF:float, #frictional resistance coefficient for actual water temperature and salinity
                                   CF0:float, #frictional resistance coefficient for reference water temperature and salinity
                                   delta_CF:float, #roughness allowance associated with Reynolds number for actual water temperature and salinity
                                   delta_CF0:float,#roughness allowance associated with Reynolds number for reference water temperature and salinity
                                   CT0:float, #total resistance coefficient for reference water temperature and salinity
                                   S:float, #wetted surface area [m2]
                                   stw:float, #ship’s speed through the water [m/s]
                                   rho_S:float, #water density for actual water temperature and salt content [kg/m3 ]
                                   rho_0:float = 1026 #water density for reference water temperature and salt content                                  
                                  )-> float: #resistance increase due to deviation of water temperature and water density [N]
    
    "Resistance due to water temperature and salinity corrected relative to the reference values"
    
    #This function can be re-written into sub-parts and all the sub-parts ouputted in a results matrix. 
    #Would this be useful?
    RF = 0.5 * rho_S* S * stw**2 * (CF + delta_CF)
    RT0 = 0.5 * rho_0 * S * stw**2 * CT0
    
    RAS =  RT0 * ( rho_S/rho_0 - 1 ) - RF* ( (CF0 + delta_CF0)/(CF + delta_CF) - 1 )
    
    return RAS
    

# %% ../nbs/01_general_functions.ipynb #836bce63
def displacement_correction(power:float, #The total ideal power during the trial [kWh],
                            trial_displacement:float, #diplacement of the ship during the trial [m^3]
                            reference_displacement:float, #diplacement of the ship during the tank test [m^3]
                            )->float: #The power corrected for the difference in displacement between the trial and the tank test
    
    """Corrects the power needed by the vessel when trial displacement differs from reference displacement"""
    return power * (reference_displacement/trial_displacement)**(2/3)

# %% ../nbs/01_general_functions.ipynb #68a461c9-a382-4786-8792-a474fa059c41
def load_datasets(dataset:str #The name of the dataset to load
                     ): #returns a dataframe containing example data
        
        "Load example datasets to try out the pyseatrials functions"
        
        #This needs to be adapted so that the paths work on any system, using pathlib.path would be a better choice
        res = pkgutil.get_data('pyseatrials', 'datasets/'+dataset+'.csv')
        
        return pd.read_csv(BytesIO(res))
