# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_wave_resistance.ipynb.

# %% auto 0
__all__ = ['stawave1_fn']

# %% ../nbs/03_wave_resistance.ipynb 2
import numpy as np
from fastcore.test import *

# %% ../nbs/03_wave_resistance.ipynb 4
def stawave1_fn(
    beam:float, #the beam of the ship [m]
    wave_height:float, #Significant wave height of wind waves [m]
    length:float, #The length of the bow on the water line [m]. See documentation for more details
    water_density:float = 1026, #this should be for the current temperature and salinity [kg/m^3]
            gravity:float  = 9.81
            )-> float: # Wave resistance [kg*m/s^2]
    
    "STAWAVE-1 finds the resistance caused by bow waves for ships experiencing low heave and pitch"
    
    
    return (1/16)* water_density * wave_height**2 * beam * np.sqrt(beam/length)
    
