# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_wind.ipynb.

# %% auto 0
__all__ = ['true_wind_speed_from_relative', 'true_wind_direction_from_relative', 'relative_wind_speed_from_true',
           'relative_wind_direction_from_true', 'vertical_position_anemometer']

# %% ../nbs/02_wind.ipynb 3
import numpy as np
import pandas as pd
from fastcore.test import *
from .trig import *


# %% ../nbs/02_wind.ipynb 6
def true_wind_speed_from_relative(relative_windspeed:float, #speed of wind relative to ship
                            sog:float, #speed over ground
                           relative_wind_direction:float #wind direction relative to ship
                           ) ->float: # True windspeed
    "converts a relative wind speed and direction to a true wind speed"
    return law_of_cosines(relative_windspeed, sog, relative_wind_direction)

# %% ../nbs/02_wind.ipynb 16
def true_wind_direction_from_relative(
    relative_wind_speed:float, #Speed of the wind relative to the ship
    sog:float, #Speed of the ship overground
    relative_wind_direction:float, #direction of wind in radians relative to the ship
    vessel_heading:float, #The direction of the ship through the water
    constrain_to_positive:bool = True #Should the function return a value between 0 and 2 pi
)-> float: # the true wind directionangle relative to north in radians.
    "converts relative wind direction to true wind direction"
    #This function should probably be abstracted to a more trignonometric form
    numerator = opposite_magnitude_fn(relative_wind_speed, relative_wind_direction + vessel_heading) - opposite_magnitude_fn(sog, vessel_heading) 
    denominator = adjacent_magnitude_fn(relative_wind_speed, relative_wind_direction + vessel_heading) - adjacent_magnitude_fn(sog, vessel_heading) 
    
    gamma = np.arctan2(numerator, denominator)
        
    #prevents negative angles if constrain to positive is true
    #using this method instead of an if statement means the function can perform vectorised operations
    gamma = gamma + 2*np.pi*(gamma<0)*constrain_to_positive
    
    return gamma 
    

# %% ../nbs/02_wind.ipynb 25
def relative_wind_speed_from_true(true_wind_speed:float, #The windspeed over ground
                            sog:float, #Speed over ground of the vessel
                            true_wind_direction:float, #Direction of wind relative to north
                            vessel_heading:float, #Direction of vessel in water relative to north
)-> float: #returns relative windspeed using the same units entered
    
    "converts true windspeed to relative"
    
    return law_of_cosines(true_wind_speed, sog,true_wind_direction - vessel_heading)

# %% ../nbs/02_wind.ipynb 31
def relative_wind_direction_from_true(
                            true_wind_speed:float, #The windspeed over ground
                            sog:float, #Speed over ground of the vessel
                            true_wind_direction:float, #Direction of wind relative to north
                            vessel_heading:float, #Direction of vessel in water relative to north
                            constrain_to_positive:bool = False #Should the function return a value between 0 and 2 pi
)-> float: #relative wind direction
    
    "converts true direction speed to relative"
    
    return find_gamma_fn(sog,true_wind_speed, true_wind_direction- vessel_heading)

# %% ../nbs/02_wind.ipynb 38
def vertical_position_anemometer(true_wind_speed:float, #True windspeed [m/s]
                                 reference_height:float, #reference heigh [m]
                                 measured_height:float  # measured height [m]
                                )-> float: #The true windspeed corrected for measurement height
    
    "Adjusts the windspeed taking into account the height of the anemometer on the ship relative to the reference height for windspeed"

    
    return true_wind_speed * (reference_height/measured_height)**(1/9)
