# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_wind_resistance_factors.ipynb.

# %% auto 0
__all__ = ['load_wind_factors']

# %% ../nbs/05_wind_resistance_factors.ipynb 2
import numpy as np
import pandas as pd
from fastcore.test import *
import pkg_resources

# %% ../nbs/05_wind_resistance_factors.ipynb 4
def load_wind_factors(vessel_type:str #The name of the vessel type. Must be one of 9 options
                     ):
    
    "Loads a data frame of the wind factors for a range of angles of attack for the named vessel type"
    
    stream = pkg_resources.resource_stream('datasets/', vessel_type+'.csv')
    return pd.read_csv(stream, encoding='latin-1')
    
    
